version: '3'

services:
  mongo_db:
    container_name: mongo_db
    image: mongo:3.4.20-xenial
    ports:
      - "27017:27017"
  api:
#    build:
#      context: https://github.com/MyEtherWallet/simplex-api.git#may_debug_and_Docker_Start
    container_name: api
    image: simplex-api
    env_file:
      - .env
    depends_on:
      - mongo_db
    ports:
      - "${API_PORT}:8080/tcp"
    environment:
      - DATA_MONGODB_HOST=mongo_db
    links:
      - mongo_db
  frontend:
    #    build:
    #      context: ./api
    container_name: frontend
    image: simplex-frontend
    env_file:
      - .env
    depends_on:
      - mongo_db
      - api
    ports:
      - "${FRONTEND_PORT}:8080/tcp"
    command: npm run prod
